#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: app_login
